name: Run The Tests
on:
  push:
  pull_request:
    types: [ opened ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16' ]
    name: Go ${{ matrix.go }} sample
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: |
        go version
        go get github.com/onsi/ginkgo/ginkgo
        go mod download
        ginkgo -r -race -p . --skipPackage=depstability_test
